[build]
builder = "NIXPACKS"
watchPaths = ["store-app/server/**"]
buildCommand = "cd store-app/server && npm install"

[deploy]
startCommand = "cd store-app/server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
