[build]
builder = "NIXPACKS"
watchPaths = ["server/**"]
buildCommand = "cd server && npm install"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
