const express = require('express');
const { supabaseAdmin } = require('../db/supabase');
const authGuard = require('../middleware/authGuard');
const permissionCheck = require('../middleware/permissionCheck');

const router = express.Router();

/**
 * GET /api/units
 * List inventory units at a location, filterable by product and status.
 * Access: All authenticated staff in the business
 */
router.get('/', authGuard, async (req, res) => {
  try {
    const { product_id, status, location_id } = req.query;

    let query = supabaseAdmin
      .from('inventory_units')
      .select(`
        *,
        product:products!product_id(id, name, sku),
        location:locations!location_id(id, name),
        qr:qr_code_pool!qr_code_id(id, code),
        assigned_by_user:users!assigned_by(id, name, email)
      `)
      .order('assigned_at', { ascending: false })
      .limit(500);

    if (req.user.role !== 'Platform Admin') {
      query = query.eq('business_id', req.user.business_id);
    }

    const loc = location_id || req.user.active_location_id;
    if (loc) query = query.eq('location_id', loc);
    if (product_id) query = query.eq('product_id', product_id);
    if (status) query = query.eq('status', status);

    const { data, error } = await query;
    if (error) throw error;
    res.json(data);
  } catch (err) {
    console.error('Error fetching units:', err);
    res.status(500).json({ error: 'Failed to fetch units' });
  }
});

/**
 * GET /api/units/lookup
 * Look up a unit by its QR code string.
 * Access: All authenticated staff
 */
router.get('/lookup', authGuard, async (req, res) => {
  try {
    const { qr } = req.query;
    if (!qr) return res.status(400).json({ error: 'QR code is required' });

    // First find the QR code in the pool
    const { data: qrRecord, error: qrErr } = await supabaseAdmin
      .from('qr_code_pool')
      .select('id, code, status')
      .eq('code', qr.trim().toUpperCase())
      .single();

    if (qrErr || !qrRecord) {
      return res.status(404).json({ error: 'QR code not found in system', code: qr });
    }

    if (qrRecord.status === 'unassigned') {
      return res.json({ qr: qrRecord, unit: null, message: 'QR code exists but is not assigned to any item.' });
    }

    // Find the inventory unit
    const { data: unit, error: unitErr } = await supabaseAdmin
      .from('inventory_units')
      .select(`
        *,
        product:products!product_id(id, name, sku, price),
        location:locations!location_id(id, name),
        qr:qr_code_pool!qr_code_id(id, code)
      `)
      .eq('qr_code_id', qrRecord.id)
      .single();

    if (unitErr || !unit) {
      return res.status(404).json({ error: 'Unit not found for this QR code' });
    }

    res.json({ qr: qrRecord, unit });
  } catch (err) {
    console.error('Error looking up unit:', err);
    res.status(500).json({ error: 'Failed to look up unit' });
  }
});

/**
 * POST /api/units/assign
 * Assign a QR code to a product at a location.
 * Scans a QR sticker → links it to product → creates unit.
 * Access: Inventory managers
 */
router.post('/assign', authGuard, permissionCheck('manage_inventory'), async (req, res) => {
  try {
    const { qr_code, pack_code, serial_number, product_id, location_id, batch_id, notes } = req.body;

    if (!product_id || !location_id) {
      return res.status(400).json({ error: 'Bad request', message: 'product_id and location_id are required.' });
    }

    // Fetch business mode
    const { data: business } = await supabaseAdmin
      .from('businesses')
      .select('qr_tracking_mode')
      .eq('id', req.user.business_id)
      .single();
    
    const isDoubleMode = business?.qr_tracking_mode === 'double';

    if (isDoubleMode) {
      if (!pack_code || !serial_number) {
        return res.status(400).json({ error: 'Bad request', message: 'pack_code and serial_number are required in Double QR Tracking Mode.' });
      }
    } else {
      if (!qr_code) {
        return res.status(400).json({ error: 'Bad request', message: 'qr_code is required in Single Tracking Mode.' });
      }
    }

    let qrRecordId = null;
    let packRecordId = null;
    let codesToUpdate = [];

    // Helper to find and validate a QR code
    const findAndValidateQR = async (codeStr, typeName) => {
      if (!codeStr) return null;
      const { data: qrRec, error: qrErr } = await supabaseAdmin
        .from('qr_code_pool')
        .select('id, code, status')
        .eq('code', codeStr.trim().toUpperCase())
        .single();

      if (qrErr || !qrRec) {
        throw { status: 404, message: `${typeName} not found in system. Ensure it was generated by Platform Admin.` };
      }
      if (qrRec.status !== 'unassigned') {
        throw { status: 400, message: `${typeName} is already ${qrRec.status}. Cannot reassign.` };
      }
      codesToUpdate.push(qrRec.id);
      return qrRec.id;
    };

    try {
      if (qr_code) qrRecordId = await findAndValidateQR(qr_code, 'Item QR Code');
      if (pack_code) packRecordId = await findAndValidateQR(pack_code, 'Pack QR Code');
    } catch (validationErr) {
      return res.status(validationErr.status || 400).json({ error: validationErr.message });
    }

    // 2. Create the inventory unit
    const { data: unit, error: unitErr } = await supabaseAdmin
      .from('inventory_units')
      .insert({
        business_id: req.user.business_id,
        product_id,
        location_id,
        qr_code_id: qrRecordId,
        pack_code_id: packRecordId,
        serial_number: serial_number || null,
        status: 'in_stock',
        batch_id: batch_id || null,
        assigned_by: req.user.id,
        notes: notes || null
      })
      .select()
      .single();

    if (unitErr) {
      if (unitErr.code === '23505') { // unique violation
        return res.status(409).json({ error: 'Serial number must be unique.' });
      }
      throw unitErr;
    }

    // 3. Update QR pool status to 'assigned'
    if (codesToUpdate.length > 0) {
      await supabaseAdmin
        .from('qr_code_pool')
        .update({ status: 'assigned' })
        .in('id', codesToUpdate);
    }

    res.status(201).json({
      message: 'Unit assigned successfully',
      unit
    });
  } catch (err) {
    console.error('Error assigning unit:', err);
    res.status(500).json({ error: 'Failed to assign unit' });
  }
});

/**
 * POST /api/units/bulk-assign
 * Assign multiple QR codes to the same product at a location.
 * Body: { qr_codes: ["QR-XXXX", "QR-YYYY", ...], product_id, location_id }
 * Access: Inventory managers
 */
router.post('/bulk-assign', authGuard, permissionCheck('manage_inventory'), async (req, res) => {
  try {
    const { qr_codes, product_id, location_id, batch_id } = req.body;

    if (!Array.isArray(qr_codes) || qr_codes.length === 0 || !product_id || !location_id) {
      return res.status(400).json({ error: 'Bad request', message: 'qr_codes array, product_id, and location_id are required.' });
    }

    const results = { assigned: 0, errors: [] };

    for (const code of qr_codes) {
      // Find QR in pool
      const { data: qrRecord } = await supabaseAdmin
        .from('qr_code_pool')
        .select('id, code, status')
        .eq('code', code.trim().toUpperCase())
        .single();

      if (!qrRecord) {
        results.errors.push({ code, reason: 'Not found in system' });
        continue;
      }

      if (qrRecord.status !== 'unassigned') {
        results.errors.push({ code, reason: `Already ${qrRecord.status}` });
        continue;
      }

      // Create unit
      const { error: unitErr } = await supabaseAdmin
        .from('inventory_units')
        .insert({
          business_id: req.user.business_id,
          product_id,
          location_id,
          qr_code_id: qrRecord.id,
          status: 'in_stock',
          batch_id: batch_id || null,
          assigned_by: req.user.id
        });

      if (unitErr) {
        results.errors.push({ code, reason: unitErr.message });
        continue;
      }

      // Update pool status
      await supabaseAdmin
        .from('qr_code_pool')
        .update({ status: 'assigned' })
        .eq('id', qrRecord.id);

      results.assigned++;
    }

    res.status(201).json({
      message: `Assigned ${results.assigned} of ${qr_codes.length} units.`,
      ...results
    });
  } catch (err) {
    console.error('Error bulk-assigning units:', err);
    res.status(500).json({ error: 'Failed to bulk-assign units' });
  }
});

/**
 * PUT /api/units/:id/status
 * Update a unit's status (damaged, lost, transferred, returned).
 * Access: Inventory managers
 */
router.put('/:id/status', authGuard, permissionCheck('manage_inventory'), async (req, res) => {
  try {
    const { id } = req.params;
    const { status, notes } = req.body;

    const validStatuses = ['in_stock', 'damaged', 'lost', 'transferred', 'returned'];
    if (!validStatuses.includes(status)) {
      return res.status(400).json({ error: `Invalid status. Must be one of: ${validStatuses.join(', ')}` });
    }

    const updateData = { status };
    if (notes) updateData.notes = notes;

    const { data, error } = await supabaseAdmin
      .from('inventory_units')
      .update(updateData)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    if (!data) return res.status(404).json({ error: 'Unit not found' });

    res.json({ message: 'Unit status updated', unit: data });
  } catch (err) {
    console.error('Error updating unit status:', err);
    res.status(500).json({ error: 'Failed to update unit status' });
  }
});

/**
 * GET /api/units/sold/:productId
 * Fetch sold units for a specific product, along with sale/customer details.
 * Implements role-based privacy for customer data.
 * Access: Managers and Admins (manage_inventory)
 */
router.get('/sold/:productId', authGuard, permissionCheck('manage_inventory'), async (req, res) => {
  try {
    const { productId } = req.params;
    const { location_id } = req.query;

    let query = supabaseAdmin
      .from('inventory_units')
      .select(`
        *,
        qr:qr_code_pool!qr_code_id(code),
        sale:sales!sold_in_sale_id(
          created_at,
          receipt_number,
          customer:customers(id, name, phone, customer_code)
        )
      `)
      .eq('product_id', productId)
      .eq('status', 'sold')
      .order('sold_at', { ascending: false });

    if (req.user.role !== 'Platform Admin') {
      query = query.eq('business_id', req.user.business_id);
    }

    if (location_id) {
      query = query.eq('location_id', location_id);
    }

    const { data, error } = await query;
    if (error) throw error;

    const isBusinessAdmin = req.user.role === 'Business Admin' || req.user.role === 'Platform Admin';

    // Map the data to enforce privacy controls
    const formattedData = data.map(unit => {
      const sale = unit.sale;
      const customer = sale ? sale.customer : null;

      // Base payload visible to all authorized (Managers, Admins)
      const payload = {
        id: unit.id,
        qr_code: unit.qr ? unit.qr.code : 'Unknown',
        sold_at: unit.sold_at || (sale ? sale.created_at : null),
        customer_code: customer ? customer.customer_code : 'Walk-in',
      };

      // Add sensitive fields only for Business Admins
      if (isBusinessAdmin) {
        payload.receipt_number = sale ? sale.receipt_number : null;
        payload.customer_name = customer ? customer.name : 'Walk-in';
        payload.customer_phone = customer ? customer.phone : '';
      }

      return payload;
    });

    res.json(formattedData);
  } catch (err) {
    console.error('Error fetching sold units:', err);
    res.status(500).json({ error: 'Failed to fetch sold units' });
  }
});

module.exports = router;
