const express = require('express');
const { supabaseAdmin } = require('../db/supabase');
const authGuard = require('../middleware/authGuard');
const permissionCheck = require('../middleware/permissionCheck');

const router = express.Router();

/**
 * GET /api/units
 * List inventory units at a location, filterable by product and status.
 * Access: All authenticated staff in the business
 */
router.get('/', authGuard, async (req, res) => {
  try {
    const { product_id, status, location_id } = req.query;

    let query = supabaseAdmin
      .from('inventory_units')
      .select(`
        *,
        product:products!product_id(id, name, sku),
        location:locations!location_id(id, name),
        qr:qr_code_pool!qr_code_id(id, code),
        assigned_by_user:users!assigned_by(id, name, email)
      `)
      .order('assigned_at', { ascending: false })
      .limit(500);

    if (req.user.role !== 'Platform Admin') {
      query = query.eq('business_id', req.user.business_id);
    }

    const loc = location_id || req.user.active_location_id;
    if (loc) query = query.eq('location_id', loc);
    if (product_id) query = query.eq('product_id', product_id);
    if (status) query = query.eq('status', status);

    const { data, error } = await query;
    if (error) throw error;
    res.json(data);
  } catch (err) {
    console.error('Error fetching units:', err);
    res.status(500).json({ error: 'Failed to fetch units' });
  }
});

/**
 * GET /api/units/lookup
 * Look up a unit by its QR code string.
 * Access: All authenticated staff
 */
router.get('/lookup', authGuard, async (req, res) => {
  try {
    const { qr } = req.query;
    if (!qr) return res.status(400).json({ error: 'QR code is required' });

    // First find the QR code in the pool
    const { data: qrRecord, error: qrErr } = await supabaseAdmin
      .from('qr_code_pool')
      .select('id, code, status')
      .eq('code', qr.trim().toUpperCase())
      .single();

    if (qrErr || !qrRecord) {
      return res.status(404).json({ error: 'QR code not found in system', code: qr });
    }

    if (qrRecord.status === 'unassigned') {
      return res.json({ qr: qrRecord, unit: null, message: 'QR code exists but is not assigned to any item.' });
    }

    // Find the inventory unit
    const { data: unit, error: unitErr } = await supabaseAdmin
      .from('inventory_units')
      .select(`
        *,
        product:products!product_id(id, name, sku, price),
        location:locations!location_id(id, name),
        qr:qr_code_pool!qr_code_id(id, code)
      `)
      .eq('qr_code_id', qrRecord.id)
      .single();

    if (unitErr || !unit) {
      return res.status(404).json({ error: 'Unit not found for this QR code' });
    }

    res.json({ qr: qrRecord, unit });
  } catch (err) {
    console.error('Error looking up unit:', err);
    res.status(500).json({ error: 'Failed to look up unit' });
  }
});

/**
 * POST /api/units/assign
 * Assign a QR code to a product at a location.
 * Scans a QR sticker → links it to product → creates unit.
 * Access: Inventory managers
 */
router.post('/assign', authGuard, permissionCheck('manage_inventory'), async (req, res) => {
  try {
    const { qr_code, product_id, location_id, batch_id, notes } = req.body;

    if (!qr_code || !product_id || !location_id) {
      return res.status(400).json({ error: 'Bad request', message: 'qr_code, product_id, and location_id are required.' });
    }

    // 1. Find the QR code in pool
    const { data: qrRecord, error: qrErr } = await supabaseAdmin
      .from('qr_code_pool')
      .select('id, code, status')
      .eq('code', qr_code.trim().toUpperCase())
      .single();

    if (qrErr || !qrRecord) {
      return res.status(404).json({ error: 'QR code not found in system. Ensure it was generated by Platform Admin.' });
    }

    if (qrRecord.status !== 'unassigned') {
      return res.status(400).json({ error: `QR code is already ${qrRecord.status}. Cannot reassign.` });
    }

    // 2. Create the inventory unit
    const { data: unit, error: unitErr } = await supabaseAdmin
      .from('inventory_units')
      .insert({
        business_id: req.user.business_id,
        product_id,
        location_id,
        qr_code_id: qrRecord.id,
        status: 'in_stock',
        batch_id: batch_id || null,
        assigned_by: req.user.id,
        notes: notes || null
      })
      .select()
      .single();

    if (unitErr) throw unitErr;

    // 3. Update QR pool status to 'assigned'
    await supabaseAdmin
      .from('qr_code_pool')
      .update({ status: 'assigned' })
      .eq('id', qrRecord.id);

    res.status(201).json({
      message: 'Unit assigned successfully',
      unit,
      qr_code: qrRecord.code
    });
  } catch (err) {
    console.error('Error assigning unit:', err);
    res.status(500).json({ error: 'Failed to assign unit' });
  }
});

/**
 * POST /api/units/bulk-assign
 * Assign multiple QR codes to the same product at a location.
 * Body: { qr_codes: ["QR-XXXX", "QR-YYYY", ...], product_id, location_id }
 * Access: Inventory managers
 */
router.post('/bulk-assign', authGuard, permissionCheck('manage_inventory'), async (req, res) => {
  try {
    const { qr_codes, product_id, location_id, batch_id } = req.body;

    if (!Array.isArray(qr_codes) || qr_codes.length === 0 || !product_id || !location_id) {
      return res.status(400).json({ error: 'Bad request', message: 'qr_codes array, product_id, and location_id are required.' });
    }

    const results = { assigned: 0, errors: [] };

    for (const code of qr_codes) {
      // Find QR in pool
      const { data: qrRecord } = await supabaseAdmin
        .from('qr_code_pool')
        .select('id, code, status')
        .eq('code', code.trim().toUpperCase())
        .single();

      if (!qrRecord) {
        results.errors.push({ code, reason: 'Not found in system' });
        continue;
      }

      if (qrRecord.status !== 'unassigned') {
        results.errors.push({ code, reason: `Already ${qrRecord.status}` });
        continue;
      }

      // Create unit
      const { error: unitErr } = await supabaseAdmin
        .from('inventory_units')
        .insert({
          business_id: req.user.business_id,
          product_id,
          location_id,
          qr_code_id: qrRecord.id,
          status: 'in_stock',
          batch_id: batch_id || null,
          assigned_by: req.user.id
        });

      if (unitErr) {
        results.errors.push({ code, reason: unitErr.message });
        continue;
      }

      // Update pool status
      await supabaseAdmin
        .from('qr_code_pool')
        .update({ status: 'assigned' })
        .eq('id', qrRecord.id);

      results.assigned++;
    }

    res.status(201).json({
      message: `Assigned ${results.assigned} of ${qr_codes.length} units.`,
      ...results
    });
  } catch (err) {
    console.error('Error bulk-assigning units:', err);
    res.status(500).json({ error: 'Failed to bulk-assign units' });
  }
});

/**
 * PUT /api/units/:id/status
 * Update a unit's status (damaged, lost, transferred, returned).
 * Access: Inventory managers
 */
router.put('/:id/status', authGuard, permissionCheck('manage_inventory'), async (req, res) => {
  try {
    const { id } = req.params;
    const { status, notes } = req.body;

    const validStatuses = ['in_stock', 'damaged', 'lost', 'transferred', 'returned'];
    if (!validStatuses.includes(status)) {
      return res.status(400).json({ error: `Invalid status. Must be one of: ${validStatuses.join(', ')}` });
    }

    const updateData = { status };
    if (notes) updateData.notes = notes;

    const { data, error } = await supabaseAdmin
      .from('inventory_units')
      .update(updateData)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    if (!data) return res.status(404).json({ error: 'Unit not found' });

    res.json({ message: 'Unit status updated', unit: data });
  } catch (err) {
    console.error('Error updating unit status:', err);
    res.status(500).json({ error: 'Failed to update unit status' });
  }
});

module.exports = router;
